name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Functions to DigitalOcean App Platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to App Platform
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: automations
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
